export default {
  react_logo: require('../assets/images/logo1.png'),
  trash: require('../assets/images/Trash.png'),
  veg: require('../assets/images/veg.png'),
  Nonveg: require('../assets/images/nonveg.png'),
  plus: require('../assets/images/plus.png'),
  minus: require('../assets/images/minus.png'),
  ic_back: require('../assets/images/ic_back.png'),
  Car:require('../assets/images/Car.png'),
  book:require('../assets/images/book.png'),
  setting:require('../assets/images/setting.png'),
  sales:require('../assets/images/sales.png'),
  dollar:require('../assets/images/dollar.png'),
  save:require('../assets/images/save.png'),
  riderOffline:require('../assets/images/riderOffline.png'),
  home:require('../assets/images/home.png'),
  Star:require('../assets/images/Star.png'),
  Cancelled:require('../assets/images/Cancelled.png'),
  India:require('../assets/images/India.png'),
  distance:require('../assets/images/distance.png'),
  corrupted:require('../assets/images/corrupted.png'),
  verify:require('../assets/images/verify.png'),
  user:require('../assets/images/user.png'),
  question:require('../assets/images/question.png'),
  credit:require('../assets/images/credit.png'),
  wallet:require('../assets/images/wallet.png'),
  info:require('../assets/images/info.png'),
  notification:require('../assets/images/notification.png'),
  file:require('../assets/images/file.png'),
  logout:require('../assets/images/logout.png'),
  smartphone:require('../assets/images/smartphone.png'),
  mail:require('../assets/images/mail.png'),
  bank:require('../assets/images/bank.png'),
  card:require('../assets/images/card.png'),
  walletHistory:require('../assets/images/walletHistory.png'),
  mark:require('../assets/images/mark.png'),
  clock:require('../assets/images/clock.png'),
  folder:require('../assets/images/folder.png'),
  ringing:require('../assets/images/ringing.png'),
  calendar:require('../assets/images/calendar.png'),
  close:require('../assets/images/close.png')
};
